### ISSUE TITLE
Etag ?!

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#8] opened 2018-03-16 09:14 UTC
"msg": "The specified If-Match header attribute does not match the existing element ETag: a new version is available. Please retrieve again the element."

during creation network (maybe already exists)

**Comment by gabstopper** [comment] 2018-03-16 11:30
Hi Remy,
If you can run with the logging settings enabled in the playbook that would help greatly. This message means the element was changed from the time the last fetch of the element was made. I'm not sure I understand the context of what operation/s you were trying to perform with this? Were you using network_element playbook/s?
Here are logging settings:
```
smc_logging:
    level: 10
    path: /Users/davidlepage/Downloads/ansible-smc.log
```
If you can rerun the attempt and send me the log that would help. ETags are used by the API to ensure that we are always operating on the latest version of that element. For example, if you fetched an element and it changed on the SMC side, then the ETag would be different.

**Comment by meandus** [comment] 2018-03-16 12:38
I have a log but there are a lot of sensible info.

What do you want to see ?

Le 16 mars 2018 12:30:39 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>If you can run with the logging settings enabled in the playbook that
>would help greatly. This message means the element was changed from the
>time the last fetch of the element was made. I'm not sure I understand
>the context of what operation/s you were trying to perform with this?
>Were you using network_element playbook/s?
>Here are logging settings:
>```
>smc_logging:
>    level: 10
>    path: /Users/davidlepage/Downloads/ansible-smc.log
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/8#issuecomment-373686640

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment] 2018-03-16 16:30
Maybe just the playbook you are trying to run and the output from the smc.log when it's running would be perfect. The ETag error will be coming from the SMC.

**Comment by gabstopper** [comment] 2018-03-20 14:36
Hi Remy,
If you reproduce this could you send me the smc log generated from the script (assuming you have the following enabled in the task):
```yaml
smc_logging:
  level: 10
  path: /Users/davidlepage/Downloads/ansible-smc.log
```
This is not necessarily a bug as ETag's are used to ensure we are always working on the latest copy of the element since smc-python caches the element data after fetching. So for example, if you fetch an element and it is subsequently modified before you attempt to modify it, the ETag's will be different and the update will fail with the ETag message above. This is a protective mechanism to ensure you do not clobber updates that might have happened on the SMC side.
Instead you are required to re fetch to grab the latest version and perform the update operation again.

**Comment by gabstopper** [comment] 2018-04-05 12:18
Hi Remy,
I'm wondering if you have seen this issue again or if I should mark this as closed (please see possible explanation above).

**Comment by gabstopper** [comment] 2018-04-06 01:09
Closing due to normal behavior. It's possible this might have been due to an smc-python change in a dev release but validated current release is free of this issue. In addition, libraries have been reworked to incorporated update_or_create logic on interfaces and other used element types to perform in place editing without excessive calls to SMC.

**Closed as completed by gabstopper** 2018-04-06 01:09 UTC
